### ISSUE TITLE
On 5.2.4 (Lua fom "Linuxbrew" - a linux port of Homebrew) running any of your scripts I get error:

### ISSUE THREAD

**Issue by JuPlutonic** [ondrejkajinek/pipe_menus#1]
Error:
` No field package.preload['libs/common']
no file '/opt/.linuxbrew/share/lua/5.2/libs/common.lua'
	no file '/opt/.linuxbrew/share/lua/5.2/libs/common/init.lua'
	no file '/opt/.linuxbrew/lib/lua/5.2/libs/common.lua'
	no file '/opt/.linuxbrew/lib/lua/5.2/libs/common/init.lua'
	no file './libs/common.lua'
	no file '/opt/.linuxbrew/lib/lua/5.2/libs/common.so'
	no file '/opt/.linuxbrew/lib/lua/5.2/loadall.so'`
[http://lua-users.org/wiki/PackagePath](this) doesn't give me any clue...

So, I want your feedback:

- what version of Lua (Lua-jit) you use? 

- I don't understand how to get included all that libraries in `local ... require` section
and why **luarocks** doesn't provide **udisks2**, **mpd**, **openboxMenu** libraries.

**Comment by ondrejkajinek** [comment]
Hi,
all my lua scripts and libs, etc., are written for lua 5.1, so issues are to be expected for 5.2 :( Missing lua modules are part of my collection of libraries and wrappers. See my bitbucket profile (ondrej_kajinek) for both repos.

Originally, I used github for my private code, few months later I switched to bitbucket.
